### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by juanito003** [kontalk/website#14]
When trying to connect on the website with https, I got this message:

kontalk.org uses an invalid security certificate. The certificate is not trusted because it was signed using a signature algorithm that was disabled because that algorithm is not secure. The certificate is only valid for the following names: beta.kontalk.net, beta.kontalk.net, kontalk.net (Error code: sec_error_cert_signature_algorithm_disabled) 

Do you plan to have a https version of the website ?

**Comment by daniele-athome** [comment]
The webserver is hosted on the same server where Kontalk Beta server is hosted (beta.kontalk.net), however port 443 is used by the server itself for future support for corporate proxy connections through HTTPS tunneling. I really don't know what we could do about it if we don't get another IP address for the server (which DigitalOcean doesn't provide) or moving the website to another server.
However... I could probably proxy Tigase through Apache and make it tunnel to Tigase when requests come to the default virtual host or to beta.kontalk.net. I will do some experiments.
Please note that certificate will be issued by CACert.org, so no support for the major browsers, sorry (we can't afford it).

**Comment by juanito003** [comment]
Hi, thanks for all the precisions, I was just curious about the https. It's ok for CACert, maybe when Mozilla will launch let's encrypt it will be easier. Never someone should have to pay for a https website. I myself run website with an autogenerated self signed certificate. So people have to click the scary "connection unsecure" warning.

Just a curious question: when 3.0.1 will go live, will you change the server name beta.kontalk.net to something else?

**Comment by daniele-athome** [comment]
Server name will remain beta.kontalk.net. It's the actual server name, it's called "beta" because it's the second server (although the first one wasn't "alpha" but "prime", but you know... naming :-).

**Comment by rugk** [comment]
> Please note that certificate will be issued by CACert.org, so no support for the major browsers, sorry (we can't afford it).

Why not just use StartSSL, a CA included in all important browsers, which also provides free certificates. Or wait until [Let's Encrypt](http://letsencrypt.org/) is ready and use certs from there.

**Comment by daniele-athome** [comment]
@rguk we've actually migrated to StartSSL recently, so no certificate trust problem.

**Comment by rugk** [comment]
https://www.kontalk.org/ still delivers a wrong certificate (wrong domain). As it's valid for https://www.kontalk.net/ I can go to https://www.kontalk.org/, but this connection also times out. The same with https://beta.kontalk.net and if I ignore the wrong-domain-warning of https://www.kontalk.org/ the same happens.

**Comment by daniele-athome** [comment]
Oh I'm sorry I didn't mean I've fixed the issue. I meant that we changed our certificate authority.

**Comment by rugk** [comment]
Okay, as I saw you finally enabled HTTPS there.
However your TLS config [is still](https://www.ssllabs.com/ssltest/analyze.html?d=kontalk.org) [bad](https://www.ssllabs.com/ssltest/analyze.html?d=kontalk.net&latest) and you should really improve it.

FYI I've [created a ruleset](https://github.com/EFForg/https-everywhere/issues/3197) for the Kontalk domains.

**Comment by daniele-athome** [comment]
Thanks @rugk. I've tried to improve it today but the server runs Debian Squeeze which is quite old and has Apache 2.2.16. I'll need to upgrade that first because for a start ECDH/ECDSA is not supported by that version.

**Comment by rugk** [comment]
Well... keeping software up-to-date is not a bad idea. :wink:

**Comment by rugk** [comment]
BTW translate.kontalk.org still uses a CAcert cert.

And you still do not seem to have updated Apache and your TLS config.

**Comment by daniele-athome** [comment]
Thanks @rugk, I know. I'm having troubles following all the Kontalk stuff because of some life and work issues. Besides, translate.kontalk.org is hosted on an old Debian version so it needs special care to update Apache.
